Repository UHHRobotics22-23/MarimbaBot, pull requests merged in 2023-05, with the labels that each got.

#95 Add CI status badge
  README.md
Labels: documentation

#17 Feature/audio
  .gitignore
  README.md
  marimbabot_audio/CMakeLists.txt
  marimbabot_audio/LICENSE.md
  marimbabot_audio/README.md
  marimbabot_audio/__init__.py
  marimbabot_audio/launch/detect_onset.launch
  marimbabot_audio/launch/marimbabot.launch
  marimbabot_audio/launch/microphone.launch
  marimbabot_audio/launch/midi.launch
  marimbabot_audio/msg/CQTStamped.msg
  marimbabot_audio/msg/NoteOnset.msg
  marimbabot_audio/package.xml
  marimbabot_audio/scripts/note2midi.py
  marimbabot_audio/scripts/onset_detection.py
  requirements.txt
Labels: audio

#64 Audio output of detected notes
  marimbabot_audio/CMakeLists.txt
  marimbabot_audio/launch/marimbabot.launch
  marimbabot_audio/package.xml
  marimbabot_audio/src/audio_from_lilypond.py
  marimbabot_bringup/launch/marimbabot.launch
  requirements.txt
Labels: enhancement, audio

#71 Mallet Planning
  README.md
  marimbabot_bringup/launch/marimbabot_ur5_bringup.launch
  marimbabot_description/launch/gazebo.launch
  marimbabot_description/launch/load_robot_description.launch
  marimbabot_description/launch/marimba_rviz.launch
  marimbabot_description/launch/marimbabot_ur5_display.launch
  marimbabot_description/urdf/marimbabot_ur5.urdf.xacro
  marimbabot_description/urdf/static_mallet_holder.urdf
  marimbabot_planning/CMakeLists.txt
  marimbabot_planning/include/marimbabot_planning/lilypond_to_hitpoint.h
  marimbabot_planning/include/marimbabot_planning/planning.h
  marimbabot_planning/src/lilypond_to_hitpoint.cpp
  marimbabot_planning/src/planning.cpp
  marimbabot_ur5_moveit_config/config/kinematics.yaml
  marimbabot_ur5_moveit_config/config/marimbabot_ur5.srdf
  marimbabot_ur5_moveit_config/launch/planning_context.launch
Labels: enhancement, motion

#113 patch for marimbabot_audio
  marimbabot_audio/LICENSE.md
  marimbabot_audio/README.md
  marimbabot_audio/__init__.py
Labels: audio

#102 Feature/speech using soundplay
  marimbabot_bringup/launch/marimbabot.launch
  marimbabot_speech/launch/marimbabot.launch
  marimbabot_speech/launch/test_speech_syntesis.launch
  marimbabot_speech/src/speech_synthesis.py
Labels: audio, behavior

#80 Gazebo simulation
  marimbabot_description/config/marimba_ur5.rviz
  marimbabot_description/launch/load_robot_description.launch
  marimbabot_description/urdf/gazebo_gripper_transmissions.xacro
  marimbabot_description/urdf/marimba.urdf.xacro
  marimbabot_description/urdf/marimbabot_ur5.urdf.xacro
  marimbabot_description/urdf/static_mallet_holder.urdf
  marimbabot_description/urdf/utilities.xacro
  marimbabot_planning/src/lilypond_to_hitpoint.cpp
  marimbabot_ur5_moveit_config/config/arm_controller_ur5.yaml
  marimbabot_ur5_moveit_config/config/gazebo_controllers.yaml
  marimbabot_ur5_moveit_config/config/gripper_controller.yaml
  marimbabot_ur5_moveit_config/config/joint_state_controller.yaml
  marimbabot_ur5_moveit_config/config/marimbabot_ur5.srdf
  marimbabot_ur5_moveit_config/launch/demo_gazebo.launch
  marimbabot_ur5_moveit_config/launch/gazebo.launch
  marimbabot_ur5_moveit_config/launch/marimbabot_gazebo.launch
  marimbabot_ur5_moveit_config/launch/moveit.rviz
  workspace.repos
Labels: simulation
