Repository UHHRobotics22-23/MarimbaBot, pull requests merged in 2023-06, with the labels that each got.

#125 Add arg to use fixed joints for bars
  marimbabot_description/urdf/marimba.urdf.xacro
  marimbabot_description/urdf/marimbabot_ur5.urdf.xacro
  marimbabot_planning/src/planning.cpp
Labels: bug

#34 Adds Action Server for connecting behaviour and planning
  marimbabot_msgs/CMakeLists.txt
  marimbabot_msgs/action/HitSequence.action
  marimbabot_msgs/msg/HitSequenceElement.msg
  marimbabot_msgs/package.xml
  marimbabot_planning/CMakeLists.txt
  marimbabot_planning/include/marimbabot_planning/lilypond_to_hitpoint.h
  marimbabot_planning/include/marimbabot_planning/planning.h
  marimbabot_planning/include/marimbabot_planning/utils.h
  marimbabot_planning/launch/marimbabot.launch
  marimbabot_planning/package.xml
  marimbabot_planning/scripts/dummy_client.py
  marimbabot_planning/src/lilypond_to_hitpoint.cpp
  marimbabot_planning/src/planning.cpp
  marimbabot_planning/src/utils.cpp
  marimbabot_vision/scripts/README.md
  marimbabot_vision/scripts/real_world_data_collection.py
Labels: motion

#127 Enable self-collisions in Gazebo
  marimbabot_bringup/launch/marimbabot_ur5_bringup.launch
  marimbabot_description/launch/marimbabot_ur5_display.launch
  marimbabot_description/launch/marimbabot_ur5_upload.launch
  marimbabot_description/urdf/marimba.urdf.xacro
  marimbabot_description/urdf/marimbabot_ur5.urdf.xacro
  marimbabot_ur5_moveit_config/launch/demo.launch
  marimbabot_ur5_moveit_config/launch/move_group.launch
  marimbabot_ur5_moveit_config/launch/planning_context.launch
  marimbabot_ur5_moveit_config/launch/run_benchmark_ompl.launch
Labels: enhancement, simulation

#136 Add prismatic bar joints for simulation
  marimbabot_description/launch/marimbabot_ur5_upload.launch
  marimbabot_ur5_moveit_config/launch/marimbabot_gazebo.launch
Labels: enhancement

#135 Separate simulation package
  marimbabot_simulation/CMakeLists.txt
  marimbabot_simulation/launch/marimbabot_gazebo.launch
  marimbabot_simulation/package.xml
  marimbabot_simulation/src/detect_bar_contact.py
Labels: enhancement

#144 move msg to marimbabot_msgs
  marimbabot_audio/CMakeLists.txt
  marimbabot_audio/package.xml
  marimbabot_audio/scripts/note2midi.py
  marimbabot_audio/scripts/onset_detection.py
  marimbabot_msgs/CMakeLists.txt
  marimbabot_msgs/msg/CQTStamped.msg
  marimbabot_msgs/msg/NoteOnset.msg
Labels: audio

#152 Rename bar frames (lowercase, s -> is)
  marimbabot_behavior/src/marimbabot_behavior/interpreter.py
  marimbabot_description/config/marimba_ur5.rviz
  marimbabot_description/urdf/marimba.urdf.xacro
  marimbabot_planning/scripts/dummy_client.py
  marimbabot_planning/scripts/keyboard_player.py
  marimbabot_planning/scripts/sound_pad.py
  marimbabot_ur5_moveit_config/config/arm_controller_ur5.yaml
  marimbabot_ur5_moveit_config/config/marimbabot_ur5.srdf
  marimbabot_ur5_moveit_config/launch/moveit.rviz
Labels: enhancement

#151 Fix synthesis node
  marimbabot_speech/CMakeLists.txt
  marimbabot_speech/package.xml
  marimbabot_speech/src/speech_synthesis.py
Labels: behavior

#146 Feature/GitHub Action build python requirements
  .github/workflows/main.yml
Labels: enhancement

#142 Feature/command recognition
  marimbabot_msgs/CMakeLists.txt
  marimbabot_msgs/msg/Command.msg
  marimbabot_msgs/msg/Speech.msg
  marimbabot_msgs/msg/TmpFile.msg
  marimbabot_speech/CMakeLists.txt
  marimbabot_speech/config/commands.txt
  marimbabot_speech/launch/marimbabot.launch
  marimbabot_speech/launch/test_speech_syntesis.launch
  marimbabot_speech/package.xml
  marimbabot_speech/setup.py
  marimbabot_speech/src/audio2tmp.py
  marimbabot_speech/src/speech2text.py
  marimbabot_speech/src/text2command.py
  marimbabot_speech/src/text2speech.py
  marimbabot_speech/src/utils/__init__.py
  marimbabot_speech/src/utils/command.py
  marimbabot_speech/src/utils/file_control.py
  requirements.txt
Labels: feature/speech

#90 add accidentals, slurs and dynamics to data generation
  marimbabot_vision/scripts/generate_data.py
Labels: vision

#156 lilypond to audio behavior integration
  marimbabot_audio/scripts/dummy_client_audio_from_lilypond.py
  marimbabot_audio/src/audio_from_lilypond.py
  marimbabot_behavior/src/marimbabot_behavior/behavior_node.py
  marimbabot_msgs/CMakeLists.txt
  marimbabot_msgs/action/LilypondAudio.action
Labels: audio, behavior
