Repository UHHRobotics22-23/MarimbaBot, pull requests merged in 2023-04, with the labels that each got.

#46 change name of the repository from robot_project to marimbabot
  README.md
Labels: organizational

#36 Add optimization notebook
  marimbabot_planning/scripts/self_calibration_optimization_example.ipynb
Labels: motion

#65 Feature/behavior
  marimbabot_behavior/CMakeLists.txt
  marimbabot_behavior/launch/marimbabot.launch
  marimbabot_behavior/package.xml
  marimbabot_behavior/src/behavior_node.py
Labels: behavior, integration

#82 add queue size to recognized_notes
  marimbabot_vision/src/vision_node.py
Labels: bug

#84 Feature/vision demo
  marimbabot_vision/config/vision_demo.rviz
  marimbabot_vision/launch/vision_demo.launch
  marimbabot_vision/src/vision_node.py
Labels: vision
